[package]
name = "spk"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
ndarray = "0.15.6"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
